triggers:
  - type: meya.api_ai
    properties:
        client_access_token: <YOUR_CLIENT_ACCESS_TOKEN>
        language: <LANGUAGE_CODE>
        intent: <INTENT_NAME>
        min_confidence: <CONFIDENCE_VALUE>